# Generated by Django 3.0.5 on 2020-04-09 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.CharField(max_length=200, verbose_name='Market id')),
                ('market_name', models.CharField(max_length=200, verbose_name='Nome do Mercado')),
            ],
            options={
                'verbose_name': 'Mercado',
                'verbose_name_plural': 'Mercados',
                'ordering': ['-market_name'],
            },
        ),
    ]
