# Generated by Django 3.0.5 on 2020-04-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_market_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em '),
        ),
    ]
