# Generated by Django 3.0.5 on 2020-04-09 18:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_auto_20200409_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
